# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.rudata.model.efir_data_hub_models_models_archive_end_of_day_on_exchange_fields import EfirDataHubModelsModelsArchiveEndOfDayOnExchangeFields  # noqa: E501
from swagger_client.rest import ApiException


class TestEfirDataHubModelsModelsArchiveEndOfDayOnExchangeFields(unittest.TestCase):
    """EfirDataHubModelsModelsArchiveEndOfDayOnExchangeFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEfirDataHubModelsModelsArchiveEndOfDayOnExchangeFields(self):
        """Test EfirDataHubModelsModelsArchiveEndOfDayOnExchangeFields"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.efir_data_hub_models_models_archive_end_of_day_on_exchange_fields.EfirDataHubModelsModelsArchiveEndOfDayOnExchangeFields()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
