# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.rudata.api.corporate_action_api import CorporateActionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCorporateActionApi(unittest.TestCase):
    """CorporateActionApi unit test stubs"""

    def setUp(self):
        self.api = CorporateActionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_corporate_action_actions_post(self):
        """Test case for v2_corporate_action_actions_post

        Получить корпоративные действия.  # noqa: E501
        """
        pass

    def test_v2_corporate_action_fields_post(self):
        """Test case for v2_corporate_action_fields_post

        Получить справочник полей по корпоративным действиям.  # noqa: E501
        """
        pass

    def test_v2_corporate_action_kind_groups_post(self):
        """Test case for v2_corporate_action_kind_groups_post

        Получить список групп видов корпоративных действий.  # noqa: E501
        """
        pass

    def test_v2_corporate_action_kinds_post(self):
        """Test case for v2_corporate_action_kinds_post

        Получить список видов корпоративных действий.  # noqa: E501
        """
        pass

    def test_v2_corporate_action_sources_post(self):
        """Test case for v2_corporate_action_sources_post

        Получить список источников информации.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
