# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.rudata.api.report_api import ReportApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReportApi(unittest.TestCase):
    """ReportApi unit test stubs"""

    def setUp(self):
        self.api = ReportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_report_cbrf_reports_file_post(self):
        """Test case for report_cbrf_reports_file_post

        Метод для выдачи ссылки на скачивание файла отчётности ЦБ РФ нового формата  # noqa: E501
        """
        pass

    def test_report_cbrf_reports_list_get(self):
        """Test case for report_cbrf_reports_list_get

        Метод для выдачи списка доступных к скачиванию файлов отчётности ЦБ РФ нового формата  # noqa: E501
        """
        pass

    def test_report_user_reports_file_post(self):
        """Test case for report_user_reports_file_post

        Позволяет получить файл отчета по имени и типу  # noqa: E501
        """
        pass

    def test_report_user_reports_list_post(self):
        """Test case for report_user_reports_list_post

        Возвращает список файлов указанного типа отчетов. Напр.: EndOfDay  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
