# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.rudata.model.efir_data_hub_models_requests_v2_bond_amortizations_ext_request import EfirDataHubModelsRequestsV2BondAmortizationsExtRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestEfirDataHubModelsRequestsV2BondAmortizationsExtRequest(unittest.TestCase):
    """EfirDataHubModelsRequestsV2BondAmortizationsExtRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEfirDataHubModelsRequestsV2BondAmortizationsExtRequest(self):
        """Test EfirDataHubModelsRequestsV2BondAmortizationsExtRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.efir_data_hub_models_requests_v2_bond_amortizations_ext_request.EfirDataHubModelsRequestsV2BondAmortizationsExtRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
