# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.rudata.model.rating_surety_ratings_agg_v2_body import RatingSuretyRatingsAggV2Body  # noqa: E501
from swagger_client.rest import ApiException


class TestRatingSuretyRatingsAggV2Body(unittest.TestCase):
    """RatingSuretyRatingsAggV2Body unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRatingSuretyRatingsAggV2Body(self):
        """Test RatingSuretyRatingsAggV2Body"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.rating_surety_ratings_agg_v2_body.RatingSuretyRatingsAggV2Body()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
