# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.rudata.api.accrued_interest_api import AccruedInterestApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccruedInterestApi(unittest.TestCase):
    """AccruedInterestApi unit test stubs"""

    def setUp(self):
        self.api = AccruedInterestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v2_accrued_interest_accrued_interest_on_date_post(self):
        """Test case for v2_accrued_interest_accrued_interest_on_date_post

        Расчет НКД на дату  # noqa: E501
        """
        pass

    def test_v2_accrued_interest_accrued_interest_on_period_post(self):
        """Test case for v2_accrued_interest_accrued_interest_on_period_post

        Расчет НКД за период  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
