# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.rudata.model.bond_amortizations_body import BondAmortizationsBody  # noqa: E501
from swagger_client.rest import ApiException


class TestBondAmortizationsBody(unittest.TestCase):
    """BondAmortizationsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBondAmortizationsBody(self):
        """Test BondAmortizationsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bond_amortizations_body.BondAmortizationsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
