# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EfirDataHubModelsModelsNsdNsdFintoolCodesFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code_nsd': 'str',
        'fintoolid': 'int',
        'code_mn': 'str',
        'code_name': 'str',
        'code': 'str',
        'nrd_sec_id': 'int'
    }

    attribute_map = {
        'code_nsd': 'code_nsd',
        'fintoolid': 'fintoolid',
        'code_mn': 'code_mn',
        'code_name': 'code_name',
        'code': 'code',
        'nrd_sec_id': 'nrd_sec_id'
    }

    def __init__(self, code_nsd=None, fintoolid=None, code_mn=None, code_name=None, code=None, nrd_sec_id=None):  # noqa: E501
        """EfirDataHubModelsModelsNsdNsdFintoolCodesFields - a model defined in Swagger"""  # noqa: E501
        self._code_nsd = None
        self._fintoolid = None
        self._code_mn = None
        self._code_name = None
        self._code = None
        self._nrd_sec_id = None
        self.discriminator = None
        if code_nsd is not None:
            self.code_nsd = code_nsd
        if fintoolid is not None:
            self.fintoolid = fintoolid
        if code_mn is not None:
            self.code_mn = code_mn
        if code_name is not None:
            self.code_name = code_name
        if code is not None:
            self.code = code
        if nrd_sec_id is not None:
            self.nrd_sec_id = nrd_sec_id

    @property
    def code_nsd(self):
        """Gets the code_nsd of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501

        Идентификатор эмитента в базе НРД  # noqa: E501

        :return: The code_nsd of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :rtype: str
        """
        return self._code_nsd

    @code_nsd.setter
    def code_nsd(self, code_nsd):
        """Sets the code_nsd of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.

        Идентификатор эмитента в базе НРД  # noqa: E501

        :param code_nsd: The code_nsd of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :type: str
        """

        self._code_nsd = code_nsd

    @property
    def fintoolid(self):
        """Gets the fintoolid of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501

        Идентификатор инструмента в базе Интерфакс  # noqa: E501

        :return: The fintoolid of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :rtype: int
        """
        return self._fintoolid

    @fintoolid.setter
    def fintoolid(self, fintoolid):
        """Sets the fintoolid of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.

        Идентификатор инструмента в базе Интерфакс  # noqa: E501

        :param fintoolid: The fintoolid of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :type: int
        """

        self._fintoolid = fintoolid

    @property
    def code_mn(self):
        """Gets the code_mn of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501

        Мнемокод типа кода  # noqa: E501

        :return: The code_mn of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :rtype: str
        """
        return self._code_mn

    @code_mn.setter
    def code_mn(self, code_mn):
        """Sets the code_mn of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.

        Мнемокод типа кода  # noqa: E501

        :param code_mn: The code_mn of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :type: str
        """

        self._code_mn = code_mn

    @property
    def code_name(self):
        """Gets the code_name of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501

        Наименование типа кода, русское  # noqa: E501

        :return: The code_name of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :rtype: str
        """
        return self._code_name

    @code_name.setter
    def code_name(self, code_name):
        """Sets the code_name of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.

        Наименование типа кода, русское  # noqa: E501

        :param code_name: The code_name of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :type: str
        """

        self._code_name = code_name

    @property
    def code(self):
        """Gets the code of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501

        Код  # noqa: E501

        :return: The code of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.

        Код  # noqa: E501

        :param code: The code of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def nrd_sec_id(self):
        """Gets the nrd_sec_id of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501

        Идентификатор бумаги в базе НРД  # noqa: E501

        :return: The nrd_sec_id of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :rtype: int
        """
        return self._nrd_sec_id

    @nrd_sec_id.setter
    def nrd_sec_id(self, nrd_sec_id):
        """Sets the nrd_sec_id of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.

        Идентификатор бумаги в базе НРД  # noqa: E501

        :param nrd_sec_id: The nrd_sec_id of this EfirDataHubModelsModelsNsdNsdFintoolCodesFields.  # noqa: E501
        :type: int
        """

        self._nrd_sec_id = nrd_sec_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EfirDataHubModelsModelsNsdNsdFintoolCodesFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EfirDataHubModelsModelsNsdNsdFintoolCodesFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
