# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'codename': 'str',
        'shortname_rus': 'str',
        'fullname_rus': 'str',
        'sort_order': 'int'
    }

    attribute_map = {
        'id': 'id',
        'codename': 'codename',
        'shortname_rus': 'shortname_rus',
        'fullname_rus': 'fullname_rus',
        'sort_order': 'sort_order'
    }

    def __init__(self, id=None, codename=None, shortname_rus=None, fullname_rus=None, sort_order=None):  # noqa: E501
        """EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._codename = None
        self._shortname_rus = None
        self._fullname_rus = None
        self._sort_order = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if codename is not None:
            self.codename = codename
        if shortname_rus is not None:
            self.shortname_rus = shortname_rus
        if fullname_rus is not None:
            self.fullname_rus = fullname_rus
        if sort_order is not None:
            self.sort_order = sort_order

    @property
    def id(self):
        """Gets the id of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501

        Идентификатор группы  # noqa: E501

        :return: The id of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.

        Идентификатор группы  # noqa: E501

        :param id: The id of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def codename(self):
        """Gets the codename of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501

        Символьный код группы  # noqa: E501

        :return: The codename of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501
        :rtype: str
        """
        return self._codename

    @codename.setter
    def codename(self, codename):
        """Sets the codename of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.

        Символьный код группы  # noqa: E501

        :param codename: The codename of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501
        :type: str
        """

        self._codename = codename

    @property
    def shortname_rus(self):
        """Gets the shortname_rus of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501

        Короткое имя на русском  # noqa: E501

        :return: The shortname_rus of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501
        :rtype: str
        """
        return self._shortname_rus

    @shortname_rus.setter
    def shortname_rus(self, shortname_rus):
        """Sets the shortname_rus of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.

        Короткое имя на русском  # noqa: E501

        :param shortname_rus: The shortname_rus of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501
        :type: str
        """

        self._shortname_rus = shortname_rus

    @property
    def fullname_rus(self):
        """Gets the fullname_rus of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501

        Полное имя на русском  # noqa: E501

        :return: The fullname_rus of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501
        :rtype: str
        """
        return self._fullname_rus

    @fullname_rus.setter
    def fullname_rus(self, fullname_rus):
        """Sets the fullname_rus of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.

        Полное имя на русском  # noqa: E501

        :param fullname_rus: The fullname_rus of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501
        :type: str
        """

        self._fullname_rus = fullname_rus

    @property
    def sort_order(self):
        """Gets the sort_order of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501

        Порядок сортировки (для удобства UI)  # noqa: E501

        :return: The sort_order of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501
        :rtype: int
        """
        return self._sort_order

    @sort_order.setter
    def sort_order(self, sort_order):
        """Sets the sort_order of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.

        Порядок сортировки (для удобства UI)  # noqa: E501

        :param sort_order: The sort_order of this EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields.  # noqa: E501
        :type: int
        """

        self._sort_order = sort_order

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EfirDataHubModelsModelsRUPriceHistoryColumnGroupsFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
