# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EfirDataHubModelsModelsRatingSecurityRatingsFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'hid': 'int',
        'code_name': 'str',
        'id_value': 'str',
        'forecast': 'str',
        'change': 'str',
        'date_award': 'datetime',
        'role': 'float',
        'okpo': 'str',
        'fininstid': 'int',
        'fintoolid': 'int',
        'isin': 'str',
        'press_release': 'str'
    }

    attribute_map = {
        'id': 'id',
        'hid': 'hid',
        'code_name': 'code_name',
        'id_value': 'id_value',
        'forecast': 'forecast',
        'change': 'change',
        'date_award': 'date_award',
        'role': 'role',
        'okpo': 'okpo',
        'fininstid': 'fininstid',
        'fintoolid': 'fintoolid',
        'isin': 'isin',
        'press_release': 'press_release'
    }

    def __init__(self, id=None, hid=None, code_name=None, id_value=None, forecast=None, change=None, date_award=None, role=None, okpo=None, fininstid=None, fintoolid=None, isin=None, press_release=None):  # noqa: E501
        """EfirDataHubModelsModelsRatingSecurityRatingsFields - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._hid = None
        self._code_name = None
        self._id_value = None
        self._forecast = None
        self._change = None
        self._date_award = None
        self._role = None
        self._okpo = None
        self._fininstid = None
        self._fintoolid = None
        self._isin = None
        self._press_release = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if hid is not None:
            self.hid = hid
        if code_name is not None:
            self.code_name = code_name
        if id_value is not None:
            self.id_value = id_value
        if forecast is not None:
            self.forecast = forecast
        if change is not None:
            self.change = change
        if date_award is not None:
            self.date_award = date_award
        if role is not None:
            self.role = role
        if okpo is not None:
            self.okpo = okpo
        if fininstid is not None:
            self.fininstid = fininstid
        if fintoolid is not None:
            self.fintoolid = fintoolid
        if isin is not None:
            self.isin = isin
        if press_release is not None:
            self.press_release = press_release

    @property
    def id(self):
        """Gets the id of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        Идентификатор рейтинга  # noqa: E501

        :return: The id of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        Идентификатор рейтинга  # noqa: E501

        :param id: The id of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def hid(self):
        """Gets the hid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        Устаревший идентификатор рейтинга  # noqa: E501

        :return: The hid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: int
        """
        return self._hid

    @hid.setter
    def hid(self, hid):
        """Sets the hid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        Устаревший идентификатор рейтинга  # noqa: E501

        :param hid: The hid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: int
        """

        self._hid = hid

    @property
    def code_name(self):
        """Gets the code_name of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        Символьный код рейтинга  # noqa: E501

        :return: The code_name of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: str
        """
        return self._code_name

    @code_name.setter
    def code_name(self, code_name):
        """Sets the code_name of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        Символьный код рейтинга  # noqa: E501

        :param code_name: The code_name of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: str
        """

        self._code_name = code_name

    @property
    def id_value(self):
        """Gets the id_value of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        Значение рейтинга  # noqa: E501

        :return: The id_value of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: str
        """
        return self._id_value

    @id_value.setter
    def id_value(self, id_value):
        """Sets the id_value of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        Значение рейтинга  # noqa: E501

        :param id_value: The id_value of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: str
        """

        self._id_value = id_value

    @property
    def forecast(self):
        """Gets the forecast of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        Прогноз рейтинга  # noqa: E501

        :return: The forecast of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: str
        """
        return self._forecast

    @forecast.setter
    def forecast(self, forecast):
        """Sets the forecast of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        Прогноз рейтинга  # noqa: E501

        :param forecast: The forecast of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: str
        """

        self._forecast = forecast

    @property
    def change(self):
        """Gets the change of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        Изменение рейтинга  # noqa: E501

        :return: The change of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: str
        """
        return self._change

    @change.setter
    def change(self, change):
        """Sets the change of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        Изменение рейтинга  # noqa: E501

        :param change: The change of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: str
        """

        self._change = change

    @property
    def date_award(self):
        """Gets the date_award of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        Дата рейтингового действия  # noqa: E501

        :return: The date_award of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: datetime
        """
        return self._date_award

    @date_award.setter
    def date_award(self, date_award):
        """Sets the date_award of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        Дата рейтингового действия  # noqa: E501

        :param date_award: The date_award of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: datetime
        """

        self._date_award = date_award

    @property
    def role(self):
        """Gets the role of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        0 – рейтинг инструмента;  1 – рейтинг эмитента;  2 – рейтинг заемщика;  3 – рейтинг гаранта или поручителя;  4 - рейтинг оферента.  # noqa: E501

        :return: The role of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: float
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        0 – рейтинг инструмента;  1 – рейтинг эмитента;  2 – рейтинг заемщика;  3 – рейтинг гаранта или поручителя;  4 - рейтинг оферента.  # noqa: E501

        :param role: The role of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: float
        """

        self._role = role

    @property
    def okpo(self):
        """Gets the okpo of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        ОКПО соответствующего организатора выпуска  # noqa: E501

        :return: The okpo of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: str
        """
        return self._okpo

    @okpo.setter
    def okpo(self, okpo):
        """Sets the okpo of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        ОКПО соответствующего организатора выпуска  # noqa: E501

        :param okpo: The okpo of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: str
        """

        self._okpo = okpo

    @property
    def fininstid(self):
        """Gets the fininstid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        Идентификатор соответствующего организатора в базе Интерфакс  # noqa: E501

        :return: The fininstid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: int
        """
        return self._fininstid

    @fininstid.setter
    def fininstid(self, fininstid):
        """Sets the fininstid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        Идентификатор соответствующего организатора в базе Интерфакс  # noqa: E501

        :param fininstid: The fininstid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: int
        """

        self._fininstid = fininstid

    @property
    def fintoolid(self):
        """Gets the fintoolid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        Идентификатор  # noqa: E501

        :return: The fintoolid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: int
        """
        return self._fintoolid

    @fintoolid.setter
    def fintoolid(self, fintoolid):
        """Sets the fintoolid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        Идентификатор  # noqa: E501

        :param fintoolid: The fintoolid of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: int
        """

        self._fintoolid = fintoolid

    @property
    def isin(self):
        """Gets the isin of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        ISIN  # noqa: E501

        :return: The isin of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: str
        """
        return self._isin

    @isin.setter
    def isin(self, isin):
        """Sets the isin of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        ISIN  # noqa: E501

        :param isin: The isin of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: str
        """

        self._isin = isin

    @property
    def press_release(self):
        """Gets the press_release of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501

        Ссылка на пресс-релиз  # noqa: E501

        :return: The press_release of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :rtype: str
        """
        return self._press_release

    @press_release.setter
    def press_release(self, press_release):
        """Sets the press_release of this EfirDataHubModelsModelsRatingSecurityRatingsFields.

        Ссылка на пресс-релиз  # noqa: E501

        :param press_release: The press_release of this EfirDataHubModelsModelsRatingSecurityRatingsFields.  # noqa: E501
        :type: str
        """

        self._press_release = press_release

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EfirDataHubModelsModelsRatingSecurityRatingsFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EfirDataHubModelsModelsRatingSecurityRatingsFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
