# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EfirDataHubModelsModelsInfoOrganizersByFininstIdFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fintooltype': 'str',
        'status': 'str',
        'begdistdate': 'datetime',
        'fintoolid': 'int',
        'fininstid': 'int',
        'id_org_role': 'int',
        'fullname': 'str',
        'note': 'str',
        'update_time': 'datetime',
        'counter': 'int',
        'rn': 'int'
    }

    attribute_map = {
        'fintooltype': 'fintooltype',
        'status': 'status',
        'begdistdate': 'begdistdate',
        'fintoolid': 'fintoolid',
        'fininstid': 'fininstid',
        'id_org_role': 'id_org_role',
        'fullname': 'fullname',
        'note': 'note',
        'update_time': 'update_time',
        'counter': 'counter',
        'rn': 'rn'
    }

    def __init__(self, fintooltype=None, status=None, begdistdate=None, fintoolid=None, fininstid=None, id_org_role=None, fullname=None, note=None, update_time=None, counter=None, rn=None):  # noqa: E501
        """EfirDataHubModelsModelsInfoOrganizersByFininstIdFields - a model defined in Swagger"""  # noqa: E501
        self._fintooltype = None
        self._status = None
        self._begdistdate = None
        self._fintoolid = None
        self._fininstid = None
        self._id_org_role = None
        self._fullname = None
        self._note = None
        self._update_time = None
        self._counter = None
        self._rn = None
        self.discriminator = None
        if fintooltype is not None:
            self.fintooltype = fintooltype
        if status is not None:
            self.status = status
        if begdistdate is not None:
            self.begdistdate = begdistdate
        if fintoolid is not None:
            self.fintoolid = fintoolid
        if fininstid is not None:
            self.fininstid = fininstid
        if id_org_role is not None:
            self.id_org_role = id_org_role
        if fullname is not None:
            self.fullname = fullname
        if note is not None:
            self.note = note
        if update_time is not None:
            self.update_time = update_time
        if counter is not None:
            self.counter = counter
        if rn is not None:
            self.rn = rn

    @property
    def fintooltype(self):
        """Gets the fintooltype of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501

        Тип бумаги  # noqa: E501

        :return: The fintooltype of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :rtype: str
        """
        return self._fintooltype

    @fintooltype.setter
    def fintooltype(self, fintooltype):
        """Sets the fintooltype of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.

        Тип бумаги  # noqa: E501

        :param fintooltype: The fintooltype of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :type: str
        """

        self._fintooltype = fintooltype

    @property
    def status(self):
        """Gets the status of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501

        Статус бумаги  # noqa: E501

        :return: The status of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.

        Статус бумаги  # noqa: E501

        :param status: The status of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def begdistdate(self):
        """Gets the begdistdate of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501

        Дата начала размещения выпуска  # noqa: E501

        :return: The begdistdate of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :rtype: datetime
        """
        return self._begdistdate

    @begdistdate.setter
    def begdistdate(self, begdistdate):
        """Sets the begdistdate of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.

        Дата начала размещения выпуска  # noqa: E501

        :param begdistdate: The begdistdate of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :type: datetime
        """

        self._begdistdate = begdistdate

    @property
    def fintoolid(self):
        """Gets the fintoolid of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501

        Идентификатор инструмента  # noqa: E501

        :return: The fintoolid of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :rtype: int
        """
        return self._fintoolid

    @fintoolid.setter
    def fintoolid(self, fintoolid):
        """Sets the fintoolid of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.

        Идентификатор инструмента  # noqa: E501

        :param fintoolid: The fintoolid of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :type: int
        """

        self._fintoolid = fintoolid

    @property
    def fininstid(self):
        """Gets the fininstid of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501

        Идентификатор организации  # noqa: E501

        :return: The fininstid of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :rtype: int
        """
        return self._fininstid

    @fininstid.setter
    def fininstid(self, fininstid):
        """Sets the fininstid of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.

        Идентификатор организации  # noqa: E501

        :param fininstid: The fininstid of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :type: int
        """

        self._fininstid = fininstid

    @property
    def id_org_role(self):
        """Gets the id_org_role of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501

        Идентификатор роли организации, применительно к данному инструменту (см. метод ListOrgRoles)  # noqa: E501

        :return: The id_org_role of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :rtype: int
        """
        return self._id_org_role

    @id_org_role.setter
    def id_org_role(self, id_org_role):
        """Sets the id_org_role of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.

        Идентификатор роли организации, применительно к данному инструменту (см. метод ListOrgRoles)  # noqa: E501

        :param id_org_role: The id_org_role of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :type: int
        """

        self._id_org_role = id_org_role

    @property
    def fullname(self):
        """Gets the fullname of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501

        Полное наименование  # noqa: E501

        :return: The fullname of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :rtype: str
        """
        return self._fullname

    @fullname.setter
    def fullname(self, fullname):
        """Sets the fullname of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.

        Полное наименование  # noqa: E501

        :param fullname: The fullname of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :type: str
        """

        self._fullname = fullname

    @property
    def note(self):
        """Gets the note of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501

        Примечание  # noqa: E501

        :return: The note of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.

        Примечание  # noqa: E501

        :param note: The note of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :type: str
        """

        self._note = note

    @property
    def update_time(self):
        """Gets the update_time of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501

        Дата обновления  # noqa: E501

        :return: The update_time of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :rtype: datetime
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.

        Дата обновления  # noqa: E501

        :param update_time: The update_time of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :type: datetime
        """

        self._update_time = update_time

    @property
    def counter(self):
        """Gets the counter of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501

        Общее количество записей в выборке  # noqa: E501

        :return: The counter of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :rtype: int
        """
        return self._counter

    @counter.setter
    def counter(self, counter):
        """Sets the counter of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.

        Общее количество записей в выборке  # noqa: E501

        :param counter: The counter of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :type: int
        """

        self._counter = counter

    @property
    def rn(self):
        """Gets the rn of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501

        Номер записи в выборке  # noqa: E501

        :return: The rn of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :rtype: int
        """
        return self._rn

    @rn.setter
    def rn(self, rn):
        """Sets the rn of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.

        Номер записи в выборке  # noqa: E501

        :param rn: The rn of this EfirDataHubModelsModelsInfoOrganizersByFininstIdFields.  # noqa: E501
        :type: int
        """

        self._rn = rn

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EfirDataHubModelsModelsInfoOrganizersByFininstIdFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EfirDataHubModelsModelsInfoOrganizersByFininstIdFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
