# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EfirDataHubModelsModelsEmitentScoringScaleFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pd': 'float',
        'ratingletters': 'str',
        'level': 'int'
    }

    attribute_map = {
        'pd': 'pd',
        'ratingletters': 'ratingletters',
        'level': 'level'
    }

    def __init__(self, pd=None, ratingletters=None, level=None):  # noqa: E501
        """EfirDataHubModelsModelsEmitentScoringScaleFields - a model defined in Swagger"""  # noqa: E501
        self._pd = None
        self._ratingletters = None
        self._level = None
        self.discriminator = None
        if pd is not None:
            self.pd = pd
        if ratingletters is not None:
            self.ratingletters = ratingletters
        if level is not None:
            self.level = level

    @property
    def pd(self):
        """Gets the pd of this EfirDataHubModelsModelsEmitentScoringScaleFields.  # noqa: E501

        Вероятность дефолта в процентах  # noqa: E501

        :return: The pd of this EfirDataHubModelsModelsEmitentScoringScaleFields.  # noqa: E501
        :rtype: float
        """
        return self._pd

    @pd.setter
    def pd(self, pd):
        """Sets the pd of this EfirDataHubModelsModelsEmitentScoringScaleFields.

        Вероятность дефолта в процентах  # noqa: E501

        :param pd: The pd of this EfirDataHubModelsModelsEmitentScoringScaleFields.  # noqa: E501
        :type: float
        """

        self._pd = pd

    @property
    def ratingletters(self):
        """Gets the ratingletters of this EfirDataHubModelsModelsEmitentScoringScaleFields.  # noqa: E501

        Символьное обозначение  # noqa: E501

        :return: The ratingletters of this EfirDataHubModelsModelsEmitentScoringScaleFields.  # noqa: E501
        :rtype: str
        """
        return self._ratingletters

    @ratingletters.setter
    def ratingletters(self, ratingletters):
        """Sets the ratingletters of this EfirDataHubModelsModelsEmitentScoringScaleFields.

        Символьное обозначение  # noqa: E501

        :param ratingletters: The ratingletters of this EfirDataHubModelsModelsEmitentScoringScaleFields.  # noqa: E501
        :type: str
        """

        self._ratingletters = ratingletters

    @property
    def level(self):
        """Gets the level of this EfirDataHubModelsModelsEmitentScoringScaleFields.  # noqa: E501

        Уровень  # noqa: E501

        :return: The level of this EfirDataHubModelsModelsEmitentScoringScaleFields.  # noqa: E501
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this EfirDataHubModelsModelsEmitentScoringScaleFields.

        Уровень  # noqa: E501

        :param level: The level of this EfirDataHubModelsModelsEmitentScoringScaleFields.  # noqa: E501
        :type: int
        """

        self._level = level

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EfirDataHubModelsModelsEmitentScoringScaleFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EfirDataHubModelsModelsEmitentScoringScaleFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
