# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EfirDataHubModelsModelsBondCovenantsFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fintool_id': 'int',
        'covenants': 'list[EfirDataHubModelsModelsBondCovenant]',
        'counter': 'int'
    }

    attribute_map = {
        'fintool_id': 'fintoolId',
        'covenants': 'covenants',
        'counter': 'counter'
    }

    def __init__(self, fintool_id=None, covenants=None, counter=None):  # noqa: E501
        """EfirDataHubModelsModelsBondCovenantsFields - a model defined in Swagger"""  # noqa: E501
        self._fintool_id = None
        self._covenants = None
        self._counter = None
        self.discriminator = None
        if fintool_id is not None:
            self.fintool_id = fintool_id
        if covenants is not None:
            self.covenants = covenants
        if counter is not None:
            self.counter = counter

    @property
    def fintool_id(self):
        """Gets the fintool_id of this EfirDataHubModelsModelsBondCovenantsFields.  # noqa: E501

        Идентификатор инструмента  # noqa: E501

        :return: The fintool_id of this EfirDataHubModelsModelsBondCovenantsFields.  # noqa: E501
        :rtype: int
        """
        return self._fintool_id

    @fintool_id.setter
    def fintool_id(self, fintool_id):
        """Sets the fintool_id of this EfirDataHubModelsModelsBondCovenantsFields.

        Идентификатор инструмента  # noqa: E501

        :param fintool_id: The fintool_id of this EfirDataHubModelsModelsBondCovenantsFields.  # noqa: E501
        :type: int
        """

        self._fintool_id = fintool_id

    @property
    def covenants(self):
        """Gets the covenants of this EfirDataHubModelsModelsBondCovenantsFields.  # noqa: E501

        Список ковенантов  # noqa: E501

        :return: The covenants of this EfirDataHubModelsModelsBondCovenantsFields.  # noqa: E501
        :rtype: list[EfirDataHubModelsModelsBondCovenant]
        """
        return self._covenants

    @covenants.setter
    def covenants(self, covenants):
        """Sets the covenants of this EfirDataHubModelsModelsBondCovenantsFields.

        Список ковенантов  # noqa: E501

        :param covenants: The covenants of this EfirDataHubModelsModelsBondCovenantsFields.  # noqa: E501
        :type: list[EfirDataHubModelsModelsBondCovenant]
        """

        self._covenants = covenants

    @property
    def counter(self):
        """Gets the counter of this EfirDataHubModelsModelsBondCovenantsFields.  # noqa: E501

        Общее количество записей в выборке  # noqa: E501

        :return: The counter of this EfirDataHubModelsModelsBondCovenantsFields.  # noqa: E501
        :rtype: int
        """
        return self._counter

    @counter.setter
    def counter(self, counter):
        """Sets the counter of this EfirDataHubModelsModelsBondCovenantsFields.

        Общее количество записей в выборке  # noqa: E501

        :param counter: The counter of this EfirDataHubModelsModelsBondCovenantsFields.  # noqa: E501
        :type: int
        """

        self._counter = counter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EfirDataHubModelsModelsBondCovenantsFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EfirDataHubModelsModelsBondCovenantsFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
