# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EfirDataHubModelsModelsDictionaryRegionsFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'id_country': 'int',
        'shortname_rus': 'str',
        'fullname_rus': 'str',
        'shortname_eng': 'str',
        'soato_code': 'str',
        'inn_code': 'str',
        'fininstid': 'int',
        'counter': 'int',
        'rn': 'int'
    }

    attribute_map = {
        'id': 'id',
        'id_country': 'id_country',
        'shortname_rus': 'shortname_rus',
        'fullname_rus': 'fullname_rus',
        'shortname_eng': 'shortname_eng',
        'soato_code': 'soato_code',
        'inn_code': 'inn_code',
        'fininstid': 'fininstid',
        'counter': 'counter',
        'rn': 'rn'
    }

    def __init__(self, id=None, id_country=None, shortname_rus=None, fullname_rus=None, shortname_eng=None, soato_code=None, inn_code=None, fininstid=None, counter=None, rn=None):  # noqa: E501
        """EfirDataHubModelsModelsDictionaryRegionsFields - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._id_country = None
        self._shortname_rus = None
        self._fullname_rus = None
        self._shortname_eng = None
        self._soato_code = None
        self._inn_code = None
        self._fininstid = None
        self._counter = None
        self._rn = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if id_country is not None:
            self.id_country = id_country
        if shortname_rus is not None:
            self.shortname_rus = shortname_rus
        if fullname_rus is not None:
            self.fullname_rus = fullname_rus
        if shortname_eng is not None:
            self.shortname_eng = shortname_eng
        if soato_code is not None:
            self.soato_code = soato_code
        if inn_code is not None:
            self.inn_code = inn_code
        if fininstid is not None:
            self.fininstid = fininstid
        if counter is not None:
            self.counter = counter
        if rn is not None:
            self.rn = rn

    @property
    def id(self):
        """Gets the id of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501

        Идентификатор региона  # noqa: E501

        :return: The id of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EfirDataHubModelsModelsDictionaryRegionsFields.

        Идентификатор региона  # noqa: E501

        :param id: The id of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def id_country(self):
        """Gets the id_country of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501

        Идентификатор страны (рус)  # noqa: E501

        :return: The id_country of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :rtype: int
        """
        return self._id_country

    @id_country.setter
    def id_country(self, id_country):
        """Sets the id_country of this EfirDataHubModelsModelsDictionaryRegionsFields.

        Идентификатор страны (рус)  # noqa: E501

        :param id_country: The id_country of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :type: int
        """

        self._id_country = id_country

    @property
    def shortname_rus(self):
        """Gets the shortname_rus of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501

        Краткое наименование (рус)  # noqa: E501

        :return: The shortname_rus of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :rtype: str
        """
        return self._shortname_rus

    @shortname_rus.setter
    def shortname_rus(self, shortname_rus):
        """Sets the shortname_rus of this EfirDataHubModelsModelsDictionaryRegionsFields.

        Краткое наименование (рус)  # noqa: E501

        :param shortname_rus: The shortname_rus of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :type: str
        """

        self._shortname_rus = shortname_rus

    @property
    def fullname_rus(self):
        """Gets the fullname_rus of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501

        Полное наименование (рус)  # noqa: E501

        :return: The fullname_rus of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :rtype: str
        """
        return self._fullname_rus

    @fullname_rus.setter
    def fullname_rus(self, fullname_rus):
        """Sets the fullname_rus of this EfirDataHubModelsModelsDictionaryRegionsFields.

        Полное наименование (рус)  # noqa: E501

        :param fullname_rus: The fullname_rus of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :type: str
        """

        self._fullname_rus = fullname_rus

    @property
    def shortname_eng(self):
        """Gets the shortname_eng of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501

        Краткое наименование (англ)  # noqa: E501

        :return: The shortname_eng of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :rtype: str
        """
        return self._shortname_eng

    @shortname_eng.setter
    def shortname_eng(self, shortname_eng):
        """Sets the shortname_eng of this EfirDataHubModelsModelsDictionaryRegionsFields.

        Краткое наименование (англ)  # noqa: E501

        :param shortname_eng: The shortname_eng of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :type: str
        """

        self._shortname_eng = shortname_eng

    @property
    def soato_code(self):
        """Gets the soato_code of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501

        Код СОАТО  # noqa: E501

        :return: The soato_code of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :rtype: str
        """
        return self._soato_code

    @soato_code.setter
    def soato_code(self, soato_code):
        """Sets the soato_code of this EfirDataHubModelsModelsDictionaryRegionsFields.

        Код СОАТО  # noqa: E501

        :param soato_code: The soato_code of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :type: str
        """

        self._soato_code = soato_code

    @property
    def inn_code(self):
        """Gets the inn_code of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501

        Код региона в ИНН  # noqa: E501

        :return: The inn_code of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :rtype: str
        """
        return self._inn_code

    @inn_code.setter
    def inn_code(self, inn_code):
        """Sets the inn_code of this EfirDataHubModelsModelsDictionaryRegionsFields.

        Код региона в ИНН  # noqa: E501

        :param inn_code: The inn_code of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :type: str
        """

        self._inn_code = inn_code

    @property
    def fininstid(self):
        """Gets the fininstid of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501

        Код органа власти региона  # noqa: E501

        :return: The fininstid of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :rtype: int
        """
        return self._fininstid

    @fininstid.setter
    def fininstid(self, fininstid):
        """Sets the fininstid of this EfirDataHubModelsModelsDictionaryRegionsFields.

        Код органа власти региона  # noqa: E501

        :param fininstid: The fininstid of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :type: int
        """

        self._fininstid = fininstid

    @property
    def counter(self):
        """Gets the counter of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501

        Общее количество записей в выборке  # noqa: E501

        :return: The counter of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :rtype: int
        """
        return self._counter

    @counter.setter
    def counter(self, counter):
        """Sets the counter of this EfirDataHubModelsModelsDictionaryRegionsFields.

        Общее количество записей в выборке  # noqa: E501

        :param counter: The counter of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :type: int
        """

        self._counter = counter

    @property
    def rn(self):
        """Gets the rn of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501

        Номер записи в выборке  # noqa: E501

        :return: The rn of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :rtype: int
        """
        return self._rn

    @rn.setter
    def rn(self, rn):
        """Sets the rn of this EfirDataHubModelsModelsDictionaryRegionsFields.

        Номер записи в выборке  # noqa: E501

        :param rn: The rn of this EfirDataHubModelsModelsDictionaryRegionsFields.  # noqa: E501
        :type: int
        """

        self._rn = rn

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EfirDataHubModelsModelsDictionaryRegionsFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EfirDataHubModelsModelsDictionaryRegionsFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
