# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EfirDataHubModelsModelsBondCovenantsInfoFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'covenant_type_id': 'int',
        'covenant_type_name': 'str'
    }

    attribute_map = {
        'covenant_type_id': 'covenant_type_id',
        'covenant_type_name': 'covenant_type_name'
    }

    def __init__(self, covenant_type_id=None, covenant_type_name=None):  # noqa: E501
        """EfirDataHubModelsModelsBondCovenantsInfoFields - a model defined in Swagger"""  # noqa: E501
        self._covenant_type_id = None
        self._covenant_type_name = None
        self.discriminator = None
        if covenant_type_id is not None:
            self.covenant_type_id = covenant_type_id
        if covenant_type_name is not None:
            self.covenant_type_name = covenant_type_name

    @property
    def covenant_type_id(self):
        """Gets the covenant_type_id of this EfirDataHubModelsModelsBondCovenantsInfoFields.  # noqa: E501

        Тип ковенанта  # noqa: E501

        :return: The covenant_type_id of this EfirDataHubModelsModelsBondCovenantsInfoFields.  # noqa: E501
        :rtype: int
        """
        return self._covenant_type_id

    @covenant_type_id.setter
    def covenant_type_id(self, covenant_type_id):
        """Sets the covenant_type_id of this EfirDataHubModelsModelsBondCovenantsInfoFields.

        Тип ковенанта  # noqa: E501

        :param covenant_type_id: The covenant_type_id of this EfirDataHubModelsModelsBondCovenantsInfoFields.  # noqa: E501
        :type: int
        """

        self._covenant_type_id = covenant_type_id

    @property
    def covenant_type_name(self):
        """Gets the covenant_type_name of this EfirDataHubModelsModelsBondCovenantsInfoFields.  # noqa: E501

        Название ковенанта  # noqa: E501

        :return: The covenant_type_name of this EfirDataHubModelsModelsBondCovenantsInfoFields.  # noqa: E501
        :rtype: str
        """
        return self._covenant_type_name

    @covenant_type_name.setter
    def covenant_type_name(self, covenant_type_name):
        """Sets the covenant_type_name of this EfirDataHubModelsModelsBondCovenantsInfoFields.

        Название ковенанта  # noqa: E501

        :param covenant_type_name: The covenant_type_name of this EfirDataHubModelsModelsBondCovenantsInfoFields.  # noqa: E501
        :type: str
        """

        self._covenant_type_name = covenant_type_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EfirDataHubModelsModelsBondCovenantsInfoFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EfirDataHubModelsModelsBondCovenantsInfoFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
