# coding: utf-8

"""
    API Reference United Data (RU DATA) v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: DataHub: v2, Models: 1.23.21.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fintool_id': 'int',
        'role_code': 'str',
        'issuer_fininst_id': 'int',
        'issuer_aggregated_rating_level': 'int',
        'issuer_rating_code': 'str',
        'issuer_rating_id': 'int',
        'issuer_rating_agency_id': 'int',
        'issuer_rating_scale_id': 'int',
        'issuer_rating_value': 'str',
        'issuer_rating_date': 'datetime'
    }

    attribute_map = {
        'fintool_id': 'fintoolId',
        'role_code': 'roleCode',
        'issuer_fininst_id': 'issuerFininstId',
        'issuer_aggregated_rating_level': 'issuerAggregatedRatingLevel',
        'issuer_rating_code': 'issuerRatingCode',
        'issuer_rating_id': 'issuerRatingId',
        'issuer_rating_agency_id': 'issuerRatingAgencyId',
        'issuer_rating_scale_id': 'issuerRatingScaleId',
        'issuer_rating_value': 'issuerRatingValue',
        'issuer_rating_date': 'issuerRatingDate'
    }

    def __init__(self, fintool_id=None, role_code=None, issuer_fininst_id=None, issuer_aggregated_rating_level=None, issuer_rating_code=None, issuer_rating_id=None, issuer_rating_agency_id=None, issuer_rating_scale_id=None, issuer_rating_value=None, issuer_rating_date=None):  # noqa: E501
        """EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields - a model defined in Swagger"""  # noqa: E501
        self._fintool_id = None
        self._role_code = None
        self._issuer_fininst_id = None
        self._issuer_aggregated_rating_level = None
        self._issuer_rating_code = None
        self._issuer_rating_id = None
        self._issuer_rating_agency_id = None
        self._issuer_rating_scale_id = None
        self._issuer_rating_value = None
        self._issuer_rating_date = None
        self.discriminator = None
        if fintool_id is not None:
            self.fintool_id = fintool_id
        if role_code is not None:
            self.role_code = role_code
        if issuer_fininst_id is not None:
            self.issuer_fininst_id = issuer_fininst_id
        if issuer_aggregated_rating_level is not None:
            self.issuer_aggregated_rating_level = issuer_aggregated_rating_level
        if issuer_rating_code is not None:
            self.issuer_rating_code = issuer_rating_code
        if issuer_rating_id is not None:
            self.issuer_rating_id = issuer_rating_id
        if issuer_rating_agency_id is not None:
            self.issuer_rating_agency_id = issuer_rating_agency_id
        if issuer_rating_scale_id is not None:
            self.issuer_rating_scale_id = issuer_rating_scale_id
        if issuer_rating_value is not None:
            self.issuer_rating_value = issuer_rating_value
        if issuer_rating_date is not None:
            self.issuer_rating_date = issuer_rating_date

    @property
    def fintool_id(self):
        """Gets the fintool_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501

        Идентификатор инструмента в базе Интерфакс  # noqa: E501

        :return: The fintool_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :rtype: int
        """
        return self._fintool_id

    @fintool_id.setter
    def fintool_id(self, fintool_id):
        """Sets the fintool_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.

        Идентификатор инструмента в базе Интерфакс  # noqa: E501

        :param fintool_id: The fintool_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :type: int
        """

        self._fintool_id = fintool_id

    @property
    def role_code(self):
        """Gets the role_code of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501

        Код роли (всегда issuer - эмитент)  # noqa: E501

        :return: The role_code of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :rtype: str
        """
        return self._role_code

    @role_code.setter
    def role_code(self, role_code):
        """Sets the role_code of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.

        Код роли (всегда issuer - эмитент)  # noqa: E501

        :param role_code: The role_code of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :type: str
        """

        self._role_code = role_code

    @property
    def issuer_fininst_id(self):
        """Gets the issuer_fininst_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501

        Идентификатор эмитента в базе Интерфакс  # noqa: E501

        :return: The issuer_fininst_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :rtype: int
        """
        return self._issuer_fininst_id

    @issuer_fininst_id.setter
    def issuer_fininst_id(self, issuer_fininst_id):
        """Sets the issuer_fininst_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.

        Идентификатор эмитента в базе Интерфакс  # noqa: E501

        :param issuer_fininst_id: The issuer_fininst_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :type: int
        """

        self._issuer_fininst_id = issuer_fininst_id

    @property
    def issuer_aggregated_rating_level(self):
        """Gets the issuer_aggregated_rating_level of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501

        Уровень рейтинга эмитента по итоговой шкале  # noqa: E501

        :return: The issuer_aggregated_rating_level of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :rtype: int
        """
        return self._issuer_aggregated_rating_level

    @issuer_aggregated_rating_level.setter
    def issuer_aggregated_rating_level(self, issuer_aggregated_rating_level):
        """Sets the issuer_aggregated_rating_level of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.

        Уровень рейтинга эмитента по итоговой шкале  # noqa: E501

        :param issuer_aggregated_rating_level: The issuer_aggregated_rating_level of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :type: int
        """

        self._issuer_aggregated_rating_level = issuer_aggregated_rating_level

    @property
    def issuer_rating_code(self):
        """Gets the issuer_rating_code of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501

        Код лучшего рейтинга эмитента или null при отсутствии рейтинга  # noqa: E501

        :return: The issuer_rating_code of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :rtype: str
        """
        return self._issuer_rating_code

    @issuer_rating_code.setter
    def issuer_rating_code(self, issuer_rating_code):
        """Sets the issuer_rating_code of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.

        Код лучшего рейтинга эмитента или null при отсутствии рейтинга  # noqa: E501

        :param issuer_rating_code: The issuer_rating_code of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :type: str
        """

        self._issuer_rating_code = issuer_rating_code

    @property
    def issuer_rating_id(self):
        """Gets the issuer_rating_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501

        Идентификатор лучшего рейтинга эмитента или null при отсутствии рейтинга  # noqa: E501

        :return: The issuer_rating_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :rtype: int
        """
        return self._issuer_rating_id

    @issuer_rating_id.setter
    def issuer_rating_id(self, issuer_rating_id):
        """Sets the issuer_rating_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.

        Идентификатор лучшего рейтинга эмитента или null при отсутствии рейтинга  # noqa: E501

        :param issuer_rating_id: The issuer_rating_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :type: int
        """

        self._issuer_rating_id = issuer_rating_id

    @property
    def issuer_rating_agency_id(self):
        """Gets the issuer_rating_agency_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501

        Идентификатор агентства, присвоившего лучший рейтинг эмитента, или null при отсутствии рейтинга  # noqa: E501

        :return: The issuer_rating_agency_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :rtype: int
        """
        return self._issuer_rating_agency_id

    @issuer_rating_agency_id.setter
    def issuer_rating_agency_id(self, issuer_rating_agency_id):
        """Sets the issuer_rating_agency_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.

        Идентификатор агентства, присвоившего лучший рейтинг эмитента, или null при отсутствии рейтинга  # noqa: E501

        :param issuer_rating_agency_id: The issuer_rating_agency_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :type: int
        """

        self._issuer_rating_agency_id = issuer_rating_agency_id

    @property
    def issuer_rating_scale_id(self):
        """Gets the issuer_rating_scale_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501

        Идентификатор шкалы лучшего рейтинга эмитента или null при отсутствии рейтинга  # noqa: E501

        :return: The issuer_rating_scale_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :rtype: int
        """
        return self._issuer_rating_scale_id

    @issuer_rating_scale_id.setter
    def issuer_rating_scale_id(self, issuer_rating_scale_id):
        """Sets the issuer_rating_scale_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.

        Идентификатор шкалы лучшего рейтинга эмитента или null при отсутствии рейтинга  # noqa: E501

        :param issuer_rating_scale_id: The issuer_rating_scale_id of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :type: int
        """

        self._issuer_rating_scale_id = issuer_rating_scale_id

    @property
    def issuer_rating_value(self):
        """Gets the issuer_rating_value of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501

        Значение лучшего рейтинга эмитента или null при отсутствии рейтинга  # noqa: E501

        :return: The issuer_rating_value of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :rtype: str
        """
        return self._issuer_rating_value

    @issuer_rating_value.setter
    def issuer_rating_value(self, issuer_rating_value):
        """Sets the issuer_rating_value of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.

        Значение лучшего рейтинга эмитента или null при отсутствии рейтинга  # noqa: E501

        :param issuer_rating_value: The issuer_rating_value of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :type: str
        """

        self._issuer_rating_value = issuer_rating_value

    @property
    def issuer_rating_date(self):
        """Gets the issuer_rating_date of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501

        Дата присвоения значения лучшего рейтинга эмитента или null при отсутствии рейтинга  # noqa: E501

        :return: The issuer_rating_date of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :rtype: datetime
        """
        return self._issuer_rating_date

    @issuer_rating_date.setter
    def issuer_rating_date(self, issuer_rating_date):
        """Sets the issuer_rating_date of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.

        Дата присвоения значения лучшего рейтинга эмитента или null при отсутствии рейтинга  # noqa: E501

        :param issuer_rating_date: The issuer_rating_date of this EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields.  # noqa: E501
        :type: datetime
        """

        self._issuer_rating_date = issuer_rating_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EfirDataHubModelsModelsSolvencyRatingAggSecurityByIssuerFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
